### ISSUE TITLE
cuttlefish schema

### ISSUE THREAD

**Issue by Licenser** [erleans/erleans#14]
It would be wonderful to have a cuttlefish schema?

**Comment by tsloughter** [comment]
It would also be wonderful if there was a rebar3 plugin that allowed `rebar3 shell` to use cuttlefish configurations :)

**Comment by cmeiklejohn** [comment]
Yeah, it seem like we should wait for the software and API to stabilize before investigating the use of ``cuttlefish``.

**Comment by tsloughter** [comment]
I'm going to close this. Reopen if anyone is actually using Erleans and wants cuttlefish :)
